# Generated by Django 4.2.16 on 2024-11-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositoptions',
            name='fin_prdt_cd',
        ),
        migrations.AddField(
            model_name='depositoptions',
            name='intr_rate_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
