# Generated by Django 4.2.16 on 2024-11-20 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='fin_co_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deposits.bank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depositoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits.depositproducts'),
        ),
        migrations.CreateModel(
            name='DepositSpecialCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.TextField()),
                ('prime_rate', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits.depositproducts')),
            ],
        ),
    ]
