# Generated by Django 4.2.4 on 2024-11-23 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposits', '0002_joined_deposits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='joined_deposits',
            new_name='JoinedDeposits',
        ),
    ]
