# Generated by Django 4.2.16 on 2024-11-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_remove_depositoptions_intr_rate_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositspecialcondition',
            name='condition_name',
            field=models.CharField(choices=[('거래 연동', '거래 연동'), ('사용 실적', '사용 실적'), ('신규 가입', '신규 가입'), ('비대면/모바일 뱅킹', '비대면/모바일 뱅킹'), ('마케팅 및 기타 동의', '마케팅 및 기타 동의'), ('기타', '기타')], max_length=20),
        ),
    ]
