# Generated by Django 4.2.4 on 2024-11-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_rename_joined_deposits_joineddeposits'),
    ]

    operations = [
        migrations.AddField(
            model_name='joineddeposits',
            name='joined_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='joineddeposits',
            name='save_trm',
            field=models.IntegerField(),
        ),
    ]
