# Generated by Django 4.2.16 on 2024-11-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0004_alter_depositspecialcondition_condition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositspecialcondition',
            name='condition_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
