# Generated by Django 4.2.16 on 2024-11-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0006_depositspecialcondition_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositspecialcondition',
            old_name='condition_name',
            new_name='condition_title',
        ),
        migrations.RemoveField(
            model_name='depositspecialcondition',
            name='fin_prdt_cd',
        ),
    ]
