# Generated by Django 4.2.4 on 2024-11-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_description',
            field=models.TextField(blank=True, null=True, verbose_name='프로필 설명'),
        ),
    ]
