# Generated by Django 4.2.16 on 2024-11-19 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='전화번호는 010-1234-5678형식이어야 합니다.', regex='\\d{3}-\\d{4}-\\d{4}$')], verbose_name='전화번호'),
        ),
    ]
