# Generated by Django 4.2.4 on 2024-11-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_description',
            field=models.TextField(blank=True, default='자기소개를 입력해주세요.', null=True, verbose_name='프로필 설명'),
        ),
    ]
